Repository Dev-FE-1/Toy_Project_3_Team3, pull requests merged in 2024-09, with the labels that each got.

#98 [feature] api 다 만듬
  package-lock.json
  package.json
  server/index.js
  server/routes/ mock.json
  server/routes/comment.js
  server/routes/commentAdd.js
  server/routes/createPlaylist.js
  server/routes/db
  server/routes/deletePlaylist.js
  server/routes/follow.js
  server/routes/followCheck.js
  server/routes/followDelete.js
  server/routes/followerPage.js
  server/routes/followers.js
  server/routes/following.js
  server/routes/followingPage.js
  server/routes/getPlaylist.js
  server/routes/like.js
  server/routes/likeAdd.js
  server/routes/likeDelete.js
  server/routes/likePage.js
  server/routes/likedPlaylists.js
  server/routes/login.js
  server/routes/myPlaylistData.js
  server/routes/passwordCheck.js
  server/routes/playListData.js
  server/routes/playlistDelete.js
  server/routes/playlistEdit.js
  server/routes/playlistPage.js
  server/routes/profile.js
  server/routes/profileEdit.js
  server/routes/profilePage.js
  server/routes/search.js
  server/routes/timeline.js
  server/routes/updateUserInfo.js
  server/routes/userProfile.js
  server/routes/watch.js
Labels: Feature

#96 [feature] fetchYoutubeData적용
  src/apis/getYoutubeData.ts
  src/components/Confirm.tsx
  src/components/createPlaylist/AddPlaylist.tsx
  src/components/createPlaylist/DraggableItem.tsx
  src/components/createPlaylist/PlaylistChart.tsx
  src/components/watch/PlaylistInfo.tsx
  src/components/watch/VideoList.tsx
  src/hooks/useYoutubeFetch.ts
  src/pages/CreatePlaylist.tsx
  src/stores/usePlaylistDataStore.ts
  src/stores/useYoutubeDataStore.ts
Labels: Feature

#100 [feature] login, signup API추가 및 연동
  server/index.js
  server/routes/createPlaylist.js
  server/routes/login.js
  server/routes/signup.js
  server/routes/signupValidate.js
  src/apis/getUserData.ts
  src/components/User.tsx
  src/components/profile/UserProfile.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/components/watch/CmmentWrite.tsx
  src/components/watch/CommentList.tsx
  src/components/watch/PlaylistInfo.tsx
  src/layout/header/HeaderActions.tsx
  src/layout/nav/FList.tsx
  src/pages/CreatePlaylist.tsx
  src/stores/useUserStore.ts
  src/types/userTypes.ts
Labels: Feature

#103 [feature] 새플리추가 서버상태 및 타입수정
  server/index.js
  server/routes/createPlaylist.js
  server/routes/youtube.js
  src/components/createPlaylist/AddPlaylist.tsx
  src/hooks/useNewPlaylist.ts
  src/pages/CreatePlaylist.tsx
  src/types/playlistTypes.ts
Labels: Feature

#105 [feat]main,like,playlist 연동
  .eslintrc.cjs
  server/routes/search.js
  src/components/Tags.tsx
  src/components/TitleHeader.tsx
  src/pages/Home.tsx
  src/pages/Like.tsx
  src/pages/Playlist.tsx
Labels: Feature

#108 [feature] API 닉네임 반환, 좋아요 체크 추가
  server/index.js
  server/routes/likeCheck.js
  server/routes/likePage.js
  server/routes/playlistPage.js
  server/routes/search.js
  server/routes/timeline.js
Labels: Feature

#109 [feature] 플레이리스트 수정기능
  server/routes/watch.js
  src/apis/cuPlyData.ts
  src/components/createPlaylist/AddPlaylist.tsx
  src/hooks/useNewPlaylist.ts
  src/hooks/useYoutubeFetch.ts
  src/pages/CreatePlaylist.tsx
  src/routes/router.tsx
  src/stores/useYoutubeDataStore.ts
  src/types/playlistTypes.ts
Labels: Feature

#112 [feature] Watch페이지 기능구현
  server/routes/youtube.js
  src/apis/getWatchData.ts
  src/apis/watch/getIsFollowing.ts
  src/apis/watch/getIsLike.ts
  src/apis/watch/postLike.ts
  src/components/User.tsx
  src/components/watch/CommentList.tsx
  src/components/watch/Comments.tsx
  src/components/watch/Player.tsx
  src/components/watch/PlaylistInfo.tsx
  src/components/watch/VideoList.tsx
  src/hooks/useLike.ts
  src/hooks/useWatchDataFetch.ts
  src/hooks/useYoutubeFetch.ts
  src/layout/nav/FollowingFollowers.tsx
  src/layout/nav/NavList.tsx
  src/pages/Home.tsx
  src/pages/Watch.tsx
  src/types/playlistTypes.ts
Labels: Feature

#113 [feature] api 핫픽스 link 길이 추가, _id 삭제
  server/routes/likePage.js
  server/routes/playlistPage.js
  server/routes/search.js
  server/routes/timeline.js
Labels: Feature

#115 [feature] 로그인, 회원가입 서버상태관리
  src/apis/creatUser.ts
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/hooks/useUserDataFetch.ts
  src/hooks/useYoutubeFetch.ts
  src/layout/header/HeaderActions.tsx
  src/layout/nav/Navbar.tsx
  src/pages/CreatePlaylist.tsx
  src/stores/useUserStore.ts
  src/types/playlistTypes.ts
  src/types/userTypes.ts
Labels: Feature

#117 [Feature] Watch페이지 기능구현 댓글작성 완료
  server/routes/watch.js
  src/apis/watch/postComment.ts
  src/apis/watch/postLike.ts
  src/apis/watch/updateFollowing.ts
  src/apis/watch/updateLike.ts
  src/components/watch/CmmentWrite.tsx
  src/components/watch/CommentList.tsx
  src/components/watch/Comments.tsx
  src/components/watch/PlaylistInfo.tsx
  src/hooks/useWatchDataFetch.ts
  src/hooks/watch/useComment.ts
  src/hooks/watch/useFollowing.ts
  src/hooks/watch/useLike.ts
  src/types/playlistTypes.ts
  src/utils/forkVideoId.ts
  src/utils/getDate.ts
Labels: Feature

#118 [feature] 주스탠드 미들웨어 사용하여 로컬스토리지에 userData저장
  server/routes/watch.js
  src/components/createPlaylist/DraggableItem.tsx
  src/components/profile/UserProfile.tsx
  src/components/sign/Signin.tsx
  src/hooks/useWatchDataFetch.ts
  src/layout/header/HeaderActions.tsx
  src/layout/nav/Logout.tsx
  src/layout/nav/Navbar.tsx
  src/pages/CreatePlaylist.tsx
  src/pages/Home.tsx
  src/pages/Like.tsx
  src/pages/Playlist.tsx
  src/pages/Timeline.tsx
  src/stores/useUserStore.ts
Labels: Feature

#123 [feature] 새플리페이지 불필요한 상태제거
  src/apis/cuPlyData.ts
  src/components/createPlaylist/AddPlaylist.tsx
  src/hooks/useNewPlaylist.ts
  src/hooks/useWatchDataFetch.ts
  src/pages/CreatePlaylist.tsx
  src/routes/router.tsx
Labels: Feature

#121 [feat] 팔로잉, 팔로워, 프로필 수정 구현
  .eslintrc.cjs
  index.html
  public/assets/fonts/Pretendard-Black.woff2
  public/assets/fonts/Pretendard-Bold.woff2
  public/assets/fonts/Pretendard-ExtraBold.woff2
  public/assets/fonts/Pretendard-ExtraLight.woff2
  public/assets/fonts/Pretendard-Light.woff2
  public/assets/fonts/Pretendard-Medium.woff2
  public/assets/fonts/Pretendard-Regular.woff2
  public/assets/fonts/Pretendard-SemiBold.woff2
  public/assets/fonts/Pretendard-Thin.woff2
  public/assets/images/banner.png
  public/assets/images/favicon.png
  public/assets/images/logo.png
  public/vite.svg
  server/routes/followerPage.js
  server/routes/followingPage.js
  src/App.tsx
  src/components/Button.tsx
  src/components/Confirm.tsx
  src/components/Input.tsx
  src/components/Logo.tsx
  src/components/MenuDot.tsx
  src/components/Modal.tsx
  src/components/Tags.tsx
  src/components/TitleHeader.tsx
  src/components/User.tsx
  src/components/VideoGridItem.tsx
  src/components/profile/ProfileEditModal.tsx
  src/components/profile/UserProfile.tsx
  src/components/sign/Signup.tsx
  src/index.css
  src/layout/Layout.tsx
  src/layout/header/HeaderActions.tsx
  src/layout/header/Search.tsx
  src/layout/nav/Banner.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/FollowingFollowers.tsx
  src/layout/nav/Logout.tsx
  src/layout/nav/Navbar.tsx
  src/pages/ErrorPage.tsx
  src/pages/Follow.tsx
  src/pages/Home.tsx
  src/pages/Like.tsx
  src/pages/Playlist.tsx
  src/pages/Profile.tsx
  src/pages/Timeline.tsx
  src/stores/useUserStore.ts
  src/styles/colors.ts
  src/styles/fonts.ts
  src/styles/global.css
  tsconfig.app.json
  vite.config.ts
Labels: Feature

#125 [feature] useEffect 의존성배열 수정, 라우터 경로 수정
  src/components/TitleHeader.tsx
  src/components/managePlaylist/AddPlaylist.tsx
  src/components/managePlaylist/DraggableItem.tsx
  src/components/managePlaylist/PlaylistChart.tsx
  src/pages/ManagePlaylist.tsx
  src/routes/router.tsx
Labels: Feature

#129 [feature] 로그인,회원가입 모달 스타일수정, 코드수정
  src/components/Modal.tsx
  src/components/managePlaylist/DraggableItem.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
Labels: Feature

#130 [fix/]화면에서만 삭제되고 서버에서 삭제 안되는 문제 해결
  src/components/MenuDot.tsx
  src/components/VideoGridItem.tsx
Labels: bug

#131 [feature] MenuDot 삭제 기능 각 컴포넌트에서 작동되도록 해결
  src/components/MenuDot.tsx
Labels: bug, Feature

#135 [feat]수정 페이지 라우팅
  src/components/MenuDot.tsx
  src/components/VideoGridItem.tsx
Labels: Feature

#133 [feature] 플리 (추가 & 수정)완료되면 경로 각각 다르게 수정 및 API호출 함수명 변경
  src/apis/updatePlyData.ts
  src/hooks/useNewPlaylist.ts
  src/pages/ManagePlaylist.tsx
Labels: Feature

#136 [feature] 로그인 여부 값 적용하여 로그인되지 않았으면 라우트 이동시 로그인 모달 띄우기
  src/layout/nav/Navbar.tsx
  src/routes/ProtectedRoutes.tsx
  src/routes/router.tsx
Labels: Feature

#139 [feature] API 핫픽스
  server/routes/likePage.js
  server/routes/playlistPage.js
Labels: Feature

#140 [bug] 플리수정할때 목록에 리시트 계속 쌓이는 오류 해결
  src/pages/Like.tsx
  src/pages/ManagePlaylist.tsx
  src/pages/Playlist.tsx
  src/pages/Timeline.tsx
  src/stores/useYoutubeDataStore.ts
Labels: bug

#141 Feat/bug fix 127
  server/routes/profilePage.js
  src/components/User.tsx
  src/components/profile/ProfileEditModal.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/FollowingFollowers.tsx
  src/pages/Profile.tsx
  src/types/userTypes.ts
Labels: Feature

#143 bug: 버그 해결 (#142)
  src/pages/Follow.tsx
  src/pages/Profile.tsx
Labels: bug

#145 [bug] managePlaylist페이지 기능오류 및 스타일 수정
  src/components/Button.tsx
  src/components/MenuDot.tsx
  src/components/managePlaylist/AddPlaylist.tsx
  src/components/managePlaylist/DraggableItem.tsx
  src/components/managePlaylist/PlaylistChart.tsx
  src/pages/ManagePlaylist.tsx
Labels: bug, design

#147 [feature] 로그인,회원가입 debounce적용 및 비밀번호재입력 추가
  package-lock.json
  server/routes/signupValidate.js
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
Labels: Feature

#148 [feat] 타임라인이 비어있을때 안나타나게 하기,캐러셀에 이미지 채우기,무한스크롤 throttle 적용
  src/components/SkeletonGridItem.tsx
  src/pages/Home.tsx
  src/pages/Like.tsx
  src/pages/Playlist.tsx
  src/pages/Timeline.tsx
Labels: Feature

#150 [feat] 메뉴닷 한번에 하나만 나오게 수정
  src/components/MenuDot.tsx
Labels: Feature

#151 [feat] 기능 오류 수정
  package-lock.json
  package.json
  server/index.js
  server/routes/nicknameCheck.js
  server/routes/uploadImage.js
  src/components/Confirm.tsx
  src/components/profile/ProfileEditModal.tsx
  src/components/profile/UserProfile.tsx
  src/pages/Follow.tsx
  src/pages/Profile.tsx
Labels: Feature

#152 [feature] 로그인 비밀번호유효성검사 추가
  server/index.js
  server/routes/signValidate.js
  server/routes/signupValidate.js
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
Labels: Feature

#153 [Feature] Watch페이지 기능 수정
  src/apis/getWatchData.ts
  src/apis/getYoutubeData.ts
  src/apis/watch/getIsFollowing.ts
  src/apis/watch/getIsLike.ts
  src/apis/watch/postComment.ts
  src/components/User.tsx
  src/components/managePlaylist/AddPlaylist.tsx
  src/components/watch/CmmentWrite.tsx
  src/components/watch/CommentList.tsx
  src/components/watch/Player.tsx
  src/components/watch/PlaylistInfo.tsx
  src/components/watch/VideoList.tsx
  src/hooks/useWatchDataFetch.ts
  src/hooks/useYoutubeFetch.ts
  src/hooks/watch/useComment.ts
  src/hooks/watch/useFollowing.ts
  src/hooks/watch/useLike.ts
  src/layout/header/HeaderActions.tsx
  src/pages/ManagePlaylist.tsx
  src/pages/Watch.tsx
Labels: Feature

#158 [feature] 로그인 시 계정유무 유효성검사 추가
  public/assets/images/user-default.png
  server/routes/signValidate.js
  server/routes/signup.js
  src/components/sign/Signin.tsx
  uploads/image-1725608592694-222867262.jpg
Labels: Feature

#161 [bug] confirm 오류 해결했습니다
  src/components/Confirm.tsx
Labels: bug

#165 [feature] 로딩 컴포넌트 만들었습니다 테스트 페이지도 만들어 놨습니다.
  src/components/Loading.tsx
  src/pages/loading.tsx
  src/routes/router.tsx
Labels: Feature

#166 [feature] 태그갯수제한 (#159)
  src/components/managePlaylist/AddPlaylist.tsx
Labels: Feature

#168 [fix] 캐러셀 오류수정,플리추가 버튼 사이즈 조절,타이틀헤더에 프로필사진에 border 컬러 추가,각페이지에서 유저정보 잘 불러오기
  src/components/TitleHeader.tsx
  src/pages/Home.tsx
  src/pages/Like.tsx
  src/pages/Playlist.tsx
Labels: Feature

#174 [Feature] 네비 팔로잉/팔로워 기능구현
  src/components/watch/PlaylistInfo.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/FollowingFollowers.tsx
  src/layout/nav/NavList.tsx
  src/pages/Watch.tsx
Labels: Feature

#172 [feature] validate API 불필요한 요청 제거
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
Labels: Feature

#176 [feature] 프로필페이지 prams, route연결
  src/apis/getUserData.ts
  src/pages/Profile.tsx
  src/routes/router.tsx
Labels: Feature

#179 [Feature] 네비 배너 수정
  public/assets/images/banner.png
  src/components/VideoGridItem.tsx
  src/pages/Home.tsx
Labels: design

#182 [feature] api 업데이트 완료
  server/routes/likePage.js
  server/routes/search.js
  server/routes/timeline.js
Labels: Feature

#186 [feature] playwright 설정 & 로그인 회원가입 테스트코드
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  tests/signupLogin.spec.ts
Labels: Feature, setting

#184 [feature] 썸네일 이미지 maxres로 설정 후 없을 시 에러처리
  src/components/managePlaylist/AddPlaylist.tsx
  src/pages/ManagePlaylist.tsx
  src/types/youtubeResponseTypes.ts
Labels: Feature

#188 [feat] 기능 오류 전체 수정
  server/routes/profilePage.js
  src/components/Input.tsx
  src/components/profile/UserProfile.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/layout/nav/NavList.tsx
  src/pages/Follow.tsx
  src/pages/Like.tsx
  src/pages/ManagePlaylist.tsx
  src/pages/Playlist.tsx
  src/pages/Profile.tsx
  src/routes/router.tsx
  uploads/image-1725697764050-11627849.jpg
Labels: Feature

#193 [feature] 로그인 인풋컴포넌트 사용
  server/routes/playlistDelete.js
  src/components/sign/Signin.tsx
Labels: Feature

#195 [feat] 프로필 페이지 오류 수정
  src/components/profile/UserProfile.tsx
  src/pages/Follow.tsx
  src/pages/Profile.tsx
Labels: Feature

#198 [Fix] 네비 팔로잉/팔로우 api연동
  src/apis/getFdata.ts
  src/hooks/useFdataFetch.ts
  src/layout/nav/FList.tsx
  src/pages/ManagePlaylist.tsx
  src/pages/Test.tsx
  src/pages/loading.tsx
  src/routes/router.tsx
  uploads/image-1725634162855-407468594.png
  uploads/image-1725635783552-34090799.png
  uploads/image-1725636221545-1250640.webp
  uploads/image-1725636315054-569637878.png
  uploads/image-1725636471938-852999929.png
Labels: bug

#200 [Feature]Watch페이지 로딩추가 , 댓글 얼럿삭제
  src/components/Loading.tsx
  src/components/watch/CmmentWrite.tsx
  src/layout/Layout.tsx
  src/pages/ManagePlaylist.tsx
  src/pages/Profile.tsx
  src/pages/Watch.tsx
Labels: Feature, design

#202 Feature/develop 201
  src/pages/Playlist.tsx
Labels: Feature

#204 [feature] 간단한 각종 코드 수정
  src/components/MenuDot.tsx
  src/components/Modal.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/layout/nav/Banner.tsx
  src/pages/ManagePlaylist.tsx
  src/routes/router.tsx
  tests/signupLogin.spec.ts
Labels: Feature

#209 [design] Watch 페이지 팔로잉버튼 수정
  src/components/Button.tsx
  src/components/watch/PlaylistInfo.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/Logout.tsx
Labels: design

#211 [feature] 테스트코드 Workflow수정
  .github/workflows/playwright.yml
Labels: Feature

#212 [feature] 테스트코드 workflow수정
  .github/workflows/playwright.yml
Labels: Feature

#210 [feat] 오류 수정, 검색 페이지 완성
  server/index.js
  server/routes/searchs.js
  src/apis/searchApi.ts
  src/components/SearchResults.tsx
  src/components/User.tsx
  src/components/profile/NicknameModal.tsx
  src/components/profile/PasswordChangeModal.tsx
  src/components/profile/ProfileImageModal.tsx
  src/components/profile/UserProfile.tsx
  src/hooks/useSearch.ts
  src/layout/header/Search.tsx
  src/layout/nav/FList.tsx
  src/pages/Follow.tsx
  src/pages/Like.tsx
  src/pages/Profile.tsx
  src/pages/SearchPage.tsx
  src/routes/router.tsx
  src/stores/useSearchStore.ts
  src/types/playlistTypes.ts
  uploads/image-1725824257770-464057283.jpg
Labels: Feature

#218 [design] 플리목록css수정
  src/components/managePlaylist/DraggableItem.tsx
  src/components/managePlaylist/PlaylistChart.tsx
Labels: design

#217 [feat] 간격 수정 (#215)
  src/components/SearchResults.tsx
Labels: design

#219 [Design] 팔로잉 버튼 통일화
  .github/workflows/playwright.yml
  src/components/Button.tsx
  src/components/profile/UserProfile.tsx
  src/pages/Follow.tsx
Labels: design

#220 [design] 플리목록 css수정
  src/components/managePlaylist/DraggableItem.tsx
Labels: design

#223 [feature] 플리목록없을시 UI없는 오류
  src/components/managePlaylist/PlaylistChart.tsx
  uploads/image-1725856649709-523686726.jpg
Labels: Feature

#228 리드미 빠르게 업데이트
  README.md
Labels: setting, design

#227 feat: 카멜케이스 수정 (#226)
  src/layout/header/Search.tsx
  src/routes/router.tsx
Labels: Feature

#229 [feature] 민태강사님 피드백반영 -> 공개여부값 토글버튼 적용
  src/components/managePlaylist/AddPlaylist.tsx
Labels: Feature, design

#234 [setting] 리드미 작성
  README.md
Labels: documentation

#233 [refector] 코드리뷰 반영한 리팩토링
  server/routes/signValidate.js
  src/apis/creatUser.ts
  src/components/MenuDot.tsx
  src/components/managePlaylist/PlaylistChart.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/pages/ManagePlaylist.tsx
  src/stores/useYoutubeDataStore.ts
Labels: enhancement

#232 멘토님 피드백 반영해서 코드 수정
  src/apis/searchApi.ts
  src/components/SearchResults.tsx
  src/components/profile/UserProfile.tsx
  src/hooks/useSearch.ts
  src/pages/ErrorPage.tsx
  src/pages/Follow.tsx
Labels: enhancement

#236 [setting] 리드미 수정
  README.md
Labels: documentation

#239 [refector] 플리 수정이후 캐싱초기화
  src/hooks/useNewPlaylist.ts
  src/pages/ManagePlaylist.tsx
Labels: enhancement

#238 [refactor] 리팩토링
  src/apis/getFdata.ts
  src/components/watch/CmmentWrite.tsx
  src/hooks/useFdataFetch.ts
  src/layout/nav/FList.tsx
  src/types/navTypes.ts
  uploads/image-1725859742417-475883731.png
  uploads/image-1725860275858-416379717.jpg
  uploads/image-1725860632524-74878022.jpg
  uploads/image-1725861229624-588608746.jpg
  uploads/image-1725861295131-984999923.jpg
  uploads/image-1725862005953-714516975.webp
  uploads/image-1725862012818-685976222.png
  uploads/image-1725862070584-689366550.jpg
  uploads/image-1725862397073-856398393.png
  uploads/image-1725864177834-715582156.png
  uploads/image-1725867201463-534411084.png
  uploads/image-1725871670183-873344741.jpg
Labels: Feature

#242 [refactor] 닉네임 유효성 검사 및 중복 체크 제출 시점에 일괄 처리하도록 변경
  src/components/profile/NicknameModal.tsx
Labels: enhancement
