Repository Dev-FE-1/Toy_Project_3_Team3, pull requests merged in 2024-08, with the labels that each got.

#6 [setting] Husky setting
  .eslintcache
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/help.yml
  .husky/commit-msg
  .husky/pre-push
  byul.config.json
  package-lock.json
  package.json
Labels: setting

#9 [feature] mongoDB연동 및 서버세팅
  .gitignore
  eslint.config.js
  package-lock.json
  package.json
  server/index.js
  src/App.tsx
  vite.config.ts
Labels: Feature

#7 Merge dev branch to Main branch
  .eslintcache
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/help.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-push
  byul.config.json
  eslint.config.js
  package-lock.json
  package.json
  server/index.js
  src/App.tsx
  vite.config.ts
Labels: setting

#16 [setting] path alias 설정 #10
  tsconfig.app.json
  vite.config.ts
Labels: setting

#20 [Fix] lint useTabs false로 변경
  README.md
  index.html
  src/App.css
  src/index.css
  tsconfig.json
  tsconfig.node.json
Labels: bug

#24 [design] colors추가
  src/styles/colors.ts
Labels: design

#27 [Design] Global css 추가
  src/styles/global.css
Labels: design

#29 [Design] 레이아웃 퍼블리싱
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/banner.png
  src/assets/logo.png
  src/components/Button.tsx
  src/components/IfElse.tsx
  src/components/Logo.tsx
  src/hooks/useResponsivNav.ts
  src/layout/Container.tsx
  src/layout/Layout.tsx
  src/layout/nav/Banner.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/FollowingFollowers.tsx
  src/layout/nav/Logout.tsx
  src/layout/nav/NavList.tsx
  src/layout/nav/NavToggle.tsx
  src/layout/nav/Navbar.tsx
  src/layout/nav/User.tsx
  src/layout/topbar/HeaderActions.tsx
  src/layout/topbar/Search.tsx
  src/layout/topbar/Topbar.tsx
  src/main.tsx
  src/stores/useNavStore.tsx
Labels: design

#32 [design] signin&signup퍼블리싱, 모달상태관리
  .husky/commit-msg
  .husky/pre-push
  package-lock.json
  package.json
  server/index.js
  src/components/Modal.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/layout/topbar/HeaderActions.tsx
  src/store/useSignModalStore.ts
Labels: design

#33 [feature] 라우팅 셋팅
  package-lock.json
  package.json
  src/App.tsx
  src/hooks/useResponsivNav.ts
  src/layout/Container.tsx
  src/layout/Layout.tsx
  src/layout/nav/NavList.tsx
  src/layout/topbar/HeaderActions.tsx
  src/pages/ErrorPage.tsx
  src/pages/Home.tsx
  src/pages/Like.tsx
  src/pages/Playlist.tsx
  src/pages/Profile.tsx
  src/pages/Timeline.tsx
  src/routes/router.tsx
  src/styles/global.css
Labels: Feature

#35 [design] 헤더,네비 css 작성을 emotion/styled에서 emotion/css로 변경
  src/components/Button.tsx
  src/components/Logo.tsx
  src/layout/Layout.tsx
  src/layout/header/Header.tsx
  src/layout/header/HeaderActions.tsx
  src/layout/header/Search.tsx
  src/layout/nav/Banner.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/FollowingFollowers.tsx
  src/layout/nav/Logout.tsx
  src/layout/nav/NavList.tsx
  src/layout/nav/NavTop.tsx
  src/layout/nav/Navbar.tsx
  src/layout/nav/User.tsx
  src/layout/topbar/Topbar.tsx
Labels: design

#38 [feature] api 세팅 했습니다
  .eslintcache
  package-lock.json
  server/index.js
Labels: Feature

#39 [feature] api 세팅 전부 완료!
  .eslintcache
  server/index.js
Labels: Feature

#41 [feature] 기존 린트 설정 적용 허스키 대체 byulhook 세팅
  .eslintcache
  .husky/commit-msg
  .husky/pre-push
  byulhook.yml
  package-lock.json
  package.json
Labels: Feature

#47 [design] 프로필퍼블리싱변동사항누락수정
  package-lock.json
  src/components/myPage/Profile.tsx
  src/pages/Follow.tsx
  src/pages/MyPage.tsx
  src/routes/router.tsx
Labels: design

#48 [Fix]eslint 설정
  .eslintrc.cjs
  .prettierrc
  byulhook.yml
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/Button.tsx
  src/components/IfElse.tsx
  src/components/Logo.tsx
  src/components/Modal.tsx
  src/components/VideoGridItem.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/hooks/useResponsivNav.ts
  src/layout/Layout.tsx
  src/layout/header/Header.tsx
  src/layout/header/HeaderActions.tsx
  src/layout/header/Search.tsx
  src/layout/nav/Banner.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/FollowingFollowers.tsx
  src/layout/nav/Logout.tsx
  src/layout/nav/NavList.tsx
  src/layout/nav/NavTop.tsx
  src/layout/nav/Navbar.tsx
  src/layout/nav/User.tsx
  src/main.tsx
  src/pages/ErrorPage.tsx
  src/pages/Home.tsx
  src/pages/Like.tsx
  src/pages/Playlist.tsx
  src/pages/Profile.tsx
  src/pages/Test.tsx
  src/pages/Timeline.tsx
  src/routes/router.tsx
  src/store/useSignModalStore.ts
  src/stores/useNavStore.tsx
  src/styles/colors.ts
  vite.config.ts
Labels: bug

#50 [feature] 로그인 기능
  package-lock.json
  package.json
  server/index.js
  src/components/Modal.tsx
  src/components/myPage/Profile.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/layout/header/HeaderActions.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/Logout.tsx
  src/layout/nav/User.tsx
  src/pages/Follow.tsx
  src/pages/MyPage.tsx
  src/pages/Profile.tsx
  src/routes/router.tsx
  src/stores/useSignModalStore.ts
  src/stores/useUserStore.ts
Labels: Feature

#51 [design] Watch 페이지 퍼블리싱
  byulhook.yml
  index.html
  package-lock.json
  package.json
  public/assets/favicon.png
  src/components/Button.tsx
  src/components/Tags.tsx
  src/components/User.tsx
  src/components/watch/Comments.tsx
  src/components/watch/Player.tsx
  src/components/watch/PlaylistInfo.tsx
  src/components/watch/VideoList.tsx
  src/layout/Layout.tsx
  src/layout/header/HeaderActions.tsx
  src/layout/nav/FList.tsx
  src/layout/nav/FollowingFollowers.tsx
  src/pages/Watch.tsx
  src/routes/router.tsx
  src/styles/global.css
  src/types/Nav.ts
  src/types/Playlist.ts
  src/types/User.ts
Labels: design

#53 [feature] 로그인 유지 작업
  src/components/profile/UserProfile.tsx
  src/components/sign/Signin.tsx
  src/layout/header/HeaderActions.tsx
  src/layout/nav/Logout.tsx
  src/layout/nav/Navbar.tsx
  src/pages/Profile.tsx
  src/routes/router.tsx
  src/types/Nav.ts
Labels: Feature

#55 [design] 메인페이지 퍼블리싱
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  src/components/VideoGridItem.tsx
  src/pages/Home.tsx
Labels: design

#65 [feat]메인 페이지 무한 스크롤 및 스켈레톤 UI 적용
  src/components/Cover.tsx
  src/components/SkeletionGridItem.tsx
  src/components/VideoGridItem.tsx
  src/data/gridItemData.ts
  src/pages/Home.tsx
  src/pages/Search.tsx
  src/routes/router.tsx
Labels: Feature

#63 [feature] 회원가입기능완료
  package-lock.json
  package.json
  server/index.js
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
Labels: Feature

#61 [Feature] Tags컴포넌트 props 설정
  src/components/Tags.tsx
  src/components/watch/PlaylistInfo.tsx
Labels: Feature

#74 [feature] 모달수정, 린트rules수정
  .eslintrc.cjs
  server/index.js
  src/components/Confirm.tsx
  src/components/Modal.tsx
  src/components/sign/Signin.tsx
  src/components/sign/Signup.tsx
  src/layout/header/HeaderActions.tsx
  src/stores/useModalStore.ts
Labels: Feature

#68 [design]like,playlist 퍼블리싱
  .husky/commit-msg
  src/components/Confirm.tsx
  src/components/Modal.tsx
  src/components/TitleHeader.tsx
  src/components/VideoGridItem.tsx
  src/components/profile/UserProfile.tsx
  src/pages/Home.tsx
  src/pages/Like.tsx
  src/pages/Playlist.tsx
Labels: design

#75 [feature] api세팅했습니다
  .prettierrc
  byul-alias.yml
  package-lock.json
  package.json
  server/index.js
  server/routes/comment.js
  server/routes/createPlaylist.js
  server/routes/deletePlaylist.js
  server/routes/followers.js
  server/routes/following.js
  server/routes/getPlaylist.js
  server/routes/like.js
  server/routes/likedPlaylists.js
  server/routes/login.js
  server/routes/myPlaylistData.js
  server/routes/playListData.js
  server/routes/signup.js
  server/routes/updateUserInfo.js
  server/routes/userProfile.js
  src/components/Modal.tsx
Labels: Feature

#76 [feat] 인풋 컴포넌트 추가
  src/components/Input.tsx
  src/styles/colors.ts
Labels: Feature

#77 [feat] 프로필 수정 모달 완료
  server/index.js
  server/routes/comment.js
  server/routes/createPlaylist.js
  server/routes/deletePlaylist.js
  server/routes/followers.js
  server/routes/following.js
  server/routes/getPlaylist.js
  server/routes/like.js
  server/routes/likedPlaylists.js
  server/routes/login.js
  server/routes/myPlaylistData.js
  server/routes/playListData.js
  server/routes/signup.js
  server/routes/updateUserInfo.js
  server/routes/userProfile.js
  src/components/Button.tsx
  src/components/Modal.tsx
  src/components/profile/UserProfile.tsx
  src/layout/header/HeaderActions.tsx
Labels: Feature

#79 [design] 새플레이리스트추가페이지 퍼블리싱
  server/index.js
  src/components/Button.tsx
  src/components/Tags.tsx
  src/components/createPlaylist/AddPlaylist.tsx
  src/components/createPlaylist/PlaylistChart.tsx
  src/pages/CreatePlaylist.tsx
  src/routes/router.tsx
Labels: design

#82 [feature] 추가된플레이리스트목록 dnd기능
  package-lock.json
  package.json
  src/components/Tags.tsx
  src/components/createPlaylist/AddPlaylist.tsx
  src/components/createPlaylist/DraggableItem.tsx
  src/components/createPlaylist/PlaylistChart.tsx
  src/main.tsx
Labels: Feature

#85 [Feat] Watch페이지 1차 기능구현
  package-lock.json
  package.json
  server/index.js
  server/routes/youtube.js
  src/App.tsx
  src/apis/getUserData.ts
  src/apis/getWatchData.ts
  src/apis/getYoutubeData.ts
  src/components/Button.tsx
  src/components/IfElse.tsx
  src/components/Logo.tsx
  src/components/User.tsx
  src/components/watch/CmmentWrite.tsx
  src/components/watch/CommentList.tsx
  src/components/watch/Comments.tsx
  src/components/watch/Player.tsx
  src/components/watch/PlaylistInfo.tsx
  src/components/watch/VideoList.tsx
  src/layout/nav/NavTop.tsx
  src/layout/nav/Navbar.tsx
  src/pages/Watch.tsx
  src/routes/router.tsx
  src/stores/useNavStore.tsx
  src/types/Playlist.ts
  src/types/User.ts
  src/types/navTypes.ts
  src/types/playlistTypes.ts
  src/types/userTypes.ts
  src/types/youtubeResponseTypes.ts
  src/utils/adjustTextAreaHeight.ts
  src/utils/forkVideoId.ts
Labels: Feature

#88 [feature]드롭다운선택적메뉴 추가 , 삭제 선택시 확인 모달
  src/components/MenuDot.tsx
  src/components/VideoGridItem.tsx
  src/pages/Home.tsx
  src/pages/Playlist.tsx
Labels: Feature

#91 [feature] 새플레이리스트추가기능
  server/index.js
  server/routes/createPlaylist.js
  server/routes/signup.js
  src/components/Button.tsx
  src/components/Confirm.tsx
  src/components/MenuDot.tsx
  src/components/Tags.tsx
  src/components/createPlaylist/AddPlaylist.tsx
  src/components/createPlaylist/DraggableItem.tsx
  src/components/createPlaylist/PlaylistChart.tsx
  src/components/sign/Signup.tsx
  src/pages/CreatePlaylist.tsx
  src/stores/usePlaylistDataStore.ts
Labels: Feature

#94 [feature] 추가 된 플레이리스트 목록 삭제
  src/components/Confirm.tsx
  src/components/createPlaylist/AddPlaylist.tsx
  src/components/createPlaylist/DraggableItem.tsx
  src/components/createPlaylist/PlaylistChart.tsx
  src/stores/usePlaylistDataStore.ts
Labels: Feature
